// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: datakeeper/datakeeper.proto

package gRPC_Distribute_File_System

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileTransferStateRequset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileTransferStateRequset) Reset() {
	*x = FileTransferStateRequset{}
	mi := &file_datakeeper_datakeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTransferStateRequset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTransferStateRequset) ProtoMessage() {}

func (x *FileTransferStateRequset) ProtoReflect() protoreflect.Message {
	mi := &file_datakeeper_datakeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTransferStateRequset.ProtoReflect.Descriptor instead.
func (*FileTransferStateRequset) Descriptor() ([]byte, []int) {
	return file_datakeeper_datakeeper_proto_rawDescGZIP(), []int{0}
}

func (x *FileTransferStateRequset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FileTransferStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileTransferStateResponse) Reset() {
	*x = FileTransferStateResponse{}
	mi := &file_datakeeper_datakeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTransferStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTransferStateResponse) ProtoMessage() {}

func (x *FileTransferStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datakeeper_datakeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTransferStateResponse.ProtoReflect.Descriptor instead.
func (*FileTransferStateResponse) Descriptor() ([]byte, []int) {
	return file_datakeeper_datakeeper_proto_rawDescGZIP(), []int{1}
}

func (x *FileTransferStateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ReplicateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateRequest) Reset() {
	*x = ReplicateRequest{}
	mi := &file_datakeeper_datakeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateRequest) ProtoMessage() {}

func (x *ReplicateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datakeeper_datakeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateRequest.ProtoReflect.Descriptor instead.
func (*ReplicateRequest) Descriptor() ([]byte, []int) {
	return file_datakeeper_datakeeper_proto_rawDescGZIP(), []int{2}
}

func (x *ReplicateRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *ReplicateRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type ReplicateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateResponse) Reset() {
	*x = ReplicateResponse{}
	mi := &file_datakeeper_datakeeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateResponse) ProtoMessage() {}

func (x *ReplicateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datakeeper_datakeeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateResponse.ProtoReflect.Descriptor instead.
func (*ReplicateResponse) Descriptor() ([]byte, []int) {
	return file_datakeeper_datakeeper_proto_rawDescGZIP(), []int{3}
}

func (x *ReplicateResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_datakeeper_datakeeper_proto protoreflect.FileDescriptor

var file_datakeeper_datakeeper_proto_rawDesc = string([]byte{
	0x0a, 0x1b, 0x64, 0x61, 0x74, 0x61, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2f, 0x64, 0x61, 0x74,
	0x61, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x67,
	0x52, 0x50, 0x43, 0x5f, 0x44, 0x46, 0x53, 0x22, 0x2e, 0x0a, 0x18, 0x46, 0x69, 0x6c, 0x65, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x73, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x33, 0x0a, 0x19, 0x46, 0x69, 0x6c, 0x65, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x3e, 0x0a, 0x10,
	0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f,
	0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x23, 0x0a, 0x11,
	0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f,
	0x6b, 0x32, 0xc1, 0x01, 0x0a, 0x12, 0x44, 0x61, 0x74, 0x61, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x61, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x46,
	0x69, 0x6c, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x22, 0x2e, 0x67, 0x52, 0x50, 0x43, 0x5f, 0x44, 0x46, 0x53, 0x2e, 0x46, 0x69, 0x6c, 0x65,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x73, 0x65, 0x74, 0x1a, 0x23, 0x2e, 0x67, 0x52, 0x50, 0x43, 0x5f, 0x44, 0x46, 0x53, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0b, 0x52,
	0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x12, 0x1a, 0x2e, 0x67, 0x52, 0x50,
	0x43, 0x5f, 0x44, 0x46, 0x53, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x67, 0x52, 0x50, 0x43, 0x5f, 0x44, 0x46,
	0x53, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x4d, 0x6f, 0x41, 0x64, 0x65, 0x6c, 0x45, 0x7a, 0x7a, 0x2f, 0x67, 0x52,
	0x50, 0x43, 0x2d, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x2d, 0x46, 0x69,
	0x6c, 0x65, 0x2d, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
})

var (
	file_datakeeper_datakeeper_proto_rawDescOnce sync.Once
	file_datakeeper_datakeeper_proto_rawDescData []byte
)

func file_datakeeper_datakeeper_proto_rawDescGZIP() []byte {
	file_datakeeper_datakeeper_proto_rawDescOnce.Do(func() {
		file_datakeeper_datakeeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datakeeper_datakeeper_proto_rawDesc), len(file_datakeeper_datakeeper_proto_rawDesc)))
	})
	return file_datakeeper_datakeeper_proto_rawDescData
}

var file_datakeeper_datakeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_datakeeper_datakeeper_proto_goTypes = []any{
	(*FileTransferStateRequset)(nil),  // 0: gRPC_DFS.FileTransferStateRequset
	(*FileTransferStateResponse)(nil), // 1: gRPC_DFS.FileTransferStateResponse
	(*ReplicateRequest)(nil),          // 2: gRPC_DFS.ReplicateRequest
	(*ReplicateResponse)(nil),         // 3: gRPC_DFS.ReplicateResponse
}
var file_datakeeper_datakeeper_proto_depIdxs = []int32{
	0, // 0: gRPC_DFS.DatakeeperServices.GetFileTransferState:input_type -> gRPC_DFS.FileTransferStateRequset
	2, // 1: gRPC_DFS.DatakeeperServices.ReplicateTo:input_type -> gRPC_DFS.ReplicateRequest
	1, // 2: gRPC_DFS.DatakeeperServices.GetFileTransferState:output_type -> gRPC_DFS.FileTransferStateResponse
	3, // 3: gRPC_DFS.DatakeeperServices.ReplicateTo:output_type -> gRPC_DFS.ReplicateResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_datakeeper_datakeeper_proto_init() }
func file_datakeeper_datakeeper_proto_init() {
	if File_datakeeper_datakeeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datakeeper_datakeeper_proto_rawDesc), len(file_datakeeper_datakeeper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_datakeeper_datakeeper_proto_goTypes,
		DependencyIndexes: file_datakeeper_datakeeper_proto_depIdxs,
		MessageInfos:      file_datakeeper_datakeeper_proto_msgTypes,
	}.Build()
	File_datakeeper_datakeeper_proto = out.File
	file_datakeeper_datakeeper_proto_goTypes = nil
	file_datakeeper_datakeeper_proto_depIdxs = nil
}
