// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: master-tracker.proto

package gRPC_Distribute_File_System

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MasterTrackerServices_SelectMachineToCopyTo_FullMethodName = "/gRPC_DFS.MasterTrackerServices/SelectMachineToCopyTo"
	MasterTrackerServices_GetSourceMachine_FullMethodName      = "/gRPC_DFS.MasterTrackerServices/GetSourceMachine"
	MasterTrackerServices_RegisterFile_FullMethodName          = "/gRPC_DFS.MasterTrackerServices/RegisterFile"
	MasterTrackerServices_SubscripeAsDataNode_FullMethodName   = "/gRPC_DFS.MasterTrackerServices/SubscripeAsDataNode"
	MasterTrackerServices_HeartBeat_FullMethodName             = "/gRPC_DFS.MasterTrackerServices/HeartBeat"
)

// MasterTrackerServicesClient is the client API for MasterTrackerServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MasterTrackerServicesClient interface {
	SelectMachineToCopyTo(ctx context.Context, in *SelectMachineRequest, opts ...grpc.CallOption) (*SelectMachineResponse, error)
	GetSourceMachine(ctx context.Context, in *GetSourceMachineRequest, opts ...grpc.CallOption) (*GetSourceMachineResponse, error)
	RegisterFile(ctx context.Context, in *RegisterFileRequest, opts ...grpc.CallOption) (*RegisterFileResponse, error)
	SubscripeAsDataNode(ctx context.Context, in *SubscripeAsDataNodeRequest, opts ...grpc.CallOption) (*SubscripeAsDataNodeResponse, error)
	HeartBeat(ctx context.Context, in *HeartBeatRequest, opts ...grpc.CallOption) (*HeartBeatResponse, error)
}

type masterTrackerServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewMasterTrackerServicesClient(cc grpc.ClientConnInterface) MasterTrackerServicesClient {
	return &masterTrackerServicesClient{cc}
}

func (c *masterTrackerServicesClient) SelectMachineToCopyTo(ctx context.Context, in *SelectMachineRequest, opts ...grpc.CallOption) (*SelectMachineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectMachineResponse)
	err := c.cc.Invoke(ctx, MasterTrackerServices_SelectMachineToCopyTo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterTrackerServicesClient) GetSourceMachine(ctx context.Context, in *GetSourceMachineRequest, opts ...grpc.CallOption) (*GetSourceMachineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSourceMachineResponse)
	err := c.cc.Invoke(ctx, MasterTrackerServices_GetSourceMachine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterTrackerServicesClient) RegisterFile(ctx context.Context, in *RegisterFileRequest, opts ...grpc.CallOption) (*RegisterFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterFileResponse)
	err := c.cc.Invoke(ctx, MasterTrackerServices_RegisterFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterTrackerServicesClient) SubscripeAsDataNode(ctx context.Context, in *SubscripeAsDataNodeRequest, opts ...grpc.CallOption) (*SubscripeAsDataNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscripeAsDataNodeResponse)
	err := c.cc.Invoke(ctx, MasterTrackerServices_SubscripeAsDataNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterTrackerServicesClient) HeartBeat(ctx context.Context, in *HeartBeatRequest, opts ...grpc.CallOption) (*HeartBeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartBeatResponse)
	err := c.cc.Invoke(ctx, MasterTrackerServices_HeartBeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterTrackerServicesServer is the server API for MasterTrackerServices service.
// All implementations must embed UnimplementedMasterTrackerServicesServer
// for forward compatibility.
type MasterTrackerServicesServer interface {
	SelectMachineToCopyTo(context.Context, *SelectMachineRequest) (*SelectMachineResponse, error)
	GetSourceMachine(context.Context, *GetSourceMachineRequest) (*GetSourceMachineResponse, error)
	RegisterFile(context.Context, *RegisterFileRequest) (*RegisterFileResponse, error)
	SubscripeAsDataNode(context.Context, *SubscripeAsDataNodeRequest) (*SubscripeAsDataNodeResponse, error)
	HeartBeat(context.Context, *HeartBeatRequest) (*HeartBeatResponse, error)
	mustEmbedUnimplementedMasterTrackerServicesServer()
}

// UnimplementedMasterTrackerServicesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMasterTrackerServicesServer struct{}

func (UnimplementedMasterTrackerServicesServer) SelectMachineToCopyTo(context.Context, *SelectMachineRequest) (*SelectMachineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectMachineToCopyTo not implemented")
}
func (UnimplementedMasterTrackerServicesServer) GetSourceMachine(context.Context, *GetSourceMachineRequest) (*GetSourceMachineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSourceMachine not implemented")
}
func (UnimplementedMasterTrackerServicesServer) RegisterFile(context.Context, *RegisterFileRequest) (*RegisterFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterFile not implemented")
}
func (UnimplementedMasterTrackerServicesServer) SubscripeAsDataNode(context.Context, *SubscripeAsDataNodeRequest) (*SubscripeAsDataNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubscripeAsDataNode not implemented")
}
func (UnimplementedMasterTrackerServicesServer) HeartBeat(context.Context, *HeartBeatRequest) (*HeartBeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HeartBeat not implemented")
}
func (UnimplementedMasterTrackerServicesServer) mustEmbedUnimplementedMasterTrackerServicesServer() {}
func (UnimplementedMasterTrackerServicesServer) testEmbeddedByValue()                               {}

// UnsafeMasterTrackerServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MasterTrackerServicesServer will
// result in compilation errors.
type UnsafeMasterTrackerServicesServer interface {
	mustEmbedUnimplementedMasterTrackerServicesServer()
}

func RegisterMasterTrackerServicesServer(s grpc.ServiceRegistrar, srv MasterTrackerServicesServer) {
	// If the following call pancis, it indicates UnimplementedMasterTrackerServicesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MasterTrackerServices_ServiceDesc, srv)
}

func _MasterTrackerServices_SelectMachineToCopyTo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterTrackerServicesServer).SelectMachineToCopyTo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterTrackerServices_SelectMachineToCopyTo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterTrackerServicesServer).SelectMachineToCopyTo(ctx, req.(*SelectMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterTrackerServices_GetSourceMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSourceMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterTrackerServicesServer).GetSourceMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterTrackerServices_GetSourceMachine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterTrackerServicesServer).GetSourceMachine(ctx, req.(*GetSourceMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterTrackerServices_RegisterFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterTrackerServicesServer).RegisterFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterTrackerServices_RegisterFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterTrackerServicesServer).RegisterFile(ctx, req.(*RegisterFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterTrackerServices_SubscripeAsDataNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscripeAsDataNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterTrackerServicesServer).SubscripeAsDataNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterTrackerServices_SubscripeAsDataNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterTrackerServicesServer).SubscripeAsDataNode(ctx, req.(*SubscripeAsDataNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterTrackerServices_HeartBeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartBeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterTrackerServicesServer).HeartBeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterTrackerServices_HeartBeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterTrackerServicesServer).HeartBeat(ctx, req.(*HeartBeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MasterTrackerServices_ServiceDesc is the grpc.ServiceDesc for MasterTrackerServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MasterTrackerServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gRPC_DFS.MasterTrackerServices",
	HandlerType: (*MasterTrackerServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SelectMachineToCopyTo",
			Handler:    _MasterTrackerServices_SelectMachineToCopyTo_Handler,
		},
		{
			MethodName: "GetSourceMachine",
			Handler:    _MasterTrackerServices_GetSourceMachine_Handler,
		},
		{
			MethodName: "RegisterFile",
			Handler:    _MasterTrackerServices_RegisterFile_Handler,
		},
		{
			MethodName: "SubscripeAsDataNode",
			Handler:    _MasterTrackerServices_SubscripeAsDataNode_Handler,
		},
		{
			MethodName: "HeartBeat",
			Handler:    _MasterTrackerServices_HeartBeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "master-tracker.proto",
}
