// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: master-tracker/client/client.proto

package gRPC_Distribute_File_System

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSourceMachineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSourceMachineRequest) Reset() {
	*x = GetSourceMachineRequest{}
	mi := &file_master_tracker_client_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSourceMachineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSourceMachineRequest) ProtoMessage() {}

func (x *GetSourceMachineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_tracker_client_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSourceMachineRequest.ProtoReflect.Descriptor instead.
func (*GetSourceMachineRequest) Descriptor() ([]byte, []int) {
	return file_master_tracker_client_client_proto_rawDescGZIP(), []int{0}
}

func (x *GetSourceMachineRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type GetSourceMachineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          int32                  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSourceMachineResponse) Reset() {
	*x = GetSourceMachineResponse{}
	mi := &file_master_tracker_client_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSourceMachineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSourceMachineResponse) ProtoMessage() {}

func (x *GetSourceMachineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_tracker_client_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSourceMachineResponse.ProtoReflect.Descriptor instead.
func (*GetSourceMachineResponse) Descriptor() ([]byte, []int) {
	return file_master_tracker_client_client_proto_rawDescGZIP(), []int{1}
}

func (x *GetSourceMachineResponse) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type SelectMachineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int32                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectMachineRequest) Reset() {
	*x = SelectMachineRequest{}
	mi := &file_master_tracker_client_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectMachineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectMachineRequest) ProtoMessage() {}

func (x *SelectMachineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_tracker_client_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectMachineRequest.ProtoReflect.Descriptor instead.
func (*SelectMachineRequest) Descriptor() ([]byte, []int) {
	return file_master_tracker_client_client_proto_rawDescGZIP(), []int{2}
}

func (x *SelectMachineRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SelectMachineRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type SelectMachineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectMachineResponse) Reset() {
	*x = SelectMachineResponse{}
	mi := &file_master_tracker_client_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectMachineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectMachineResponse) ProtoMessage() {}

func (x *SelectMachineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_tracker_client_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectMachineResponse.ProtoReflect.Descriptor instead.
func (*SelectMachineResponse) Descriptor() ([]byte, []int) {
	return file_master_tracker_client_client_proto_rawDescGZIP(), []int{3}
}

func (x *SelectMachineResponse) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *SelectMachineResponse) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

var File_master_tracker_client_client_proto protoreflect.FileDescriptor

var file_master_tracker_client_client_proto_rawDesc = string([]byte{
	0x0a, 0x22, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2d, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72,
	0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x67, 0x52, 0x50, 0x43, 0x5f, 0x44, 0x46, 0x53, 0x22, 0x35,
	0x0a, 0x17, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c,
	0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c,
	0x65, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2e, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x46, 0x0a, 0x14, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x4d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3b, 0x0a,
	0x15, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x32, 0xce, 0x01, 0x0a, 0x15, 0x4d,
	0x61, 0x73, 0x74, 0x65, 0x72, 0x32, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x12, 0x5a, 0x0a, 0x15, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x4d, 0x61,
	0x63, 0x68, 0x69, 0x6e, 0x65, 0x54, 0x6f, 0x43, 0x6f, 0x70, 0x79, 0x54, 0x6f, 0x12, 0x1e, 0x2e,
	0x67, 0x52, 0x50, 0x43, 0x5f, 0x44, 0x46, 0x53, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x4d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e,
	0x67, 0x52, 0x50, 0x43, 0x5f, 0x44, 0x46, 0x53, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x4d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x59, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x61, 0x63,
	0x68, 0x69, 0x6e, 0x65, 0x12, 0x21, 0x2e, 0x67, 0x52, 0x50, 0x43, 0x5f, 0x44, 0x46, 0x53, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x67, 0x52, 0x50, 0x43, 0x5f, 0x44,
	0x46, 0x53, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x32, 0x5a, 0x30, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4d, 0x6f, 0x41, 0x64, 0x65, 0x6c,
	0x45, 0x7a, 0x7a, 0x2f, 0x67, 0x52, 0x50, 0x43, 0x2d, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x2d, 0x46, 0x69, 0x6c, 0x65, 0x2d, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_master_tracker_client_client_proto_rawDescOnce sync.Once
	file_master_tracker_client_client_proto_rawDescData []byte
)

func file_master_tracker_client_client_proto_rawDescGZIP() []byte {
	file_master_tracker_client_client_proto_rawDescOnce.Do(func() {
		file_master_tracker_client_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_master_tracker_client_client_proto_rawDesc), len(file_master_tracker_client_client_proto_rawDesc)))
	})
	return file_master_tracker_client_client_proto_rawDescData
}

var file_master_tracker_client_client_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_master_tracker_client_client_proto_goTypes = []any{
	(*GetSourceMachineRequest)(nil),  // 0: gRPC_DFS.GetSourceMachineRequest
	(*GetSourceMachineResponse)(nil), // 1: gRPC_DFS.GetSourceMachineResponse
	(*SelectMachineRequest)(nil),     // 2: gRPC_DFS.SelectMachineRequest
	(*SelectMachineResponse)(nil),    // 3: gRPC_DFS.SelectMachineResponse
}
var file_master_tracker_client_client_proto_depIdxs = []int32{
	2, // 0: gRPC_DFS.Master2ClientServices.SelectMachineToCopyTo:input_type -> gRPC_DFS.SelectMachineRequest
	0, // 1: gRPC_DFS.Master2ClientServices.GetSourceMachine:input_type -> gRPC_DFS.GetSourceMachineRequest
	3, // 2: gRPC_DFS.Master2ClientServices.SelectMachineToCopyTo:output_type -> gRPC_DFS.SelectMachineResponse
	1, // 3: gRPC_DFS.Master2ClientServices.GetSourceMachine:output_type -> gRPC_DFS.GetSourceMachineResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_master_tracker_client_client_proto_init() }
func file_master_tracker_client_client_proto_init() {
	if File_master_tracker_client_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_master_tracker_client_client_proto_rawDesc), len(file_master_tracker_client_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_master_tracker_client_client_proto_goTypes,
		DependencyIndexes: file_master_tracker_client_client_proto_depIdxs,
		MessageInfos:      file_master_tracker_client_client_proto_msgTypes,
	}.Build()
	File_master_tracker_client_client_proto = out.File
	file_master_tracker_client_client_proto_goTypes = nil
	file_master_tracker_client_client_proto_depIdxs = nil
}
