// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: datanode.proto

package Distubted_File_System

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DatakeeperServices_GetFileTransferState_FullMethodName = "/DFS.DatakeeperServices/GetFileTransferState"
	DatakeeperServices_ReplicateTo_FullMethodName          = "/DFS.DatakeeperServices/ReplicateTo"
)

// DatakeeperServicesClient is the client API for DatakeeperServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DatakeeperServicesClient interface {
	GetFileTransferState(ctx context.Context, in *FileTransferStateRequset, opts ...grpc.CallOption) (*FileTransferStateResponse, error)
	ReplicateTo(ctx context.Context, in *ReplicateRequest, opts ...grpc.CallOption) (*ReplicateResponse, error)
}

type datakeeperServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewDatakeeperServicesClient(cc grpc.ClientConnInterface) DatakeeperServicesClient {
	return &datakeeperServicesClient{cc}
}

func (c *datakeeperServicesClient) GetFileTransferState(ctx context.Context, in *FileTransferStateRequset, opts ...grpc.CallOption) (*FileTransferStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileTransferStateResponse)
	err := c.cc.Invoke(ctx, DatakeeperServices_GetFileTransferState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datakeeperServicesClient) ReplicateTo(ctx context.Context, in *ReplicateRequest, opts ...grpc.CallOption) (*ReplicateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicateResponse)
	err := c.cc.Invoke(ctx, DatakeeperServices_ReplicateTo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatakeeperServicesServer is the server API for DatakeeperServices service.
// All implementations must embed UnimplementedDatakeeperServicesServer
// for forward compatibility.
type DatakeeperServicesServer interface {
	GetFileTransferState(context.Context, *FileTransferStateRequset) (*FileTransferStateResponse, error)
	ReplicateTo(context.Context, *ReplicateRequest) (*ReplicateResponse, error)
	mustEmbedUnimplementedDatakeeperServicesServer()
}

// UnimplementedDatakeeperServicesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDatakeeperServicesServer struct{}

func (UnimplementedDatakeeperServicesServer) GetFileTransferState(context.Context, *FileTransferStateRequset) (*FileTransferStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFileTransferState not implemented")
}
func (UnimplementedDatakeeperServicesServer) ReplicateTo(context.Context, *ReplicateRequest) (*ReplicateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplicateTo not implemented")
}
func (UnimplementedDatakeeperServicesServer) mustEmbedUnimplementedDatakeeperServicesServer() {}
func (UnimplementedDatakeeperServicesServer) testEmbeddedByValue()                            {}

// UnsafeDatakeeperServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatakeeperServicesServer will
// result in compilation errors.
type UnsafeDatakeeperServicesServer interface {
	mustEmbedUnimplementedDatakeeperServicesServer()
}

func RegisterDatakeeperServicesServer(s grpc.ServiceRegistrar, srv DatakeeperServicesServer) {
	// If the following call pancis, it indicates UnimplementedDatakeeperServicesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DatakeeperServices_ServiceDesc, srv)
}

func _DatakeeperServices_GetFileTransferState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileTransferStateRequset)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatakeeperServicesServer).GetFileTransferState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatakeeperServices_GetFileTransferState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatakeeperServicesServer).GetFileTransferState(ctx, req.(*FileTransferStateRequset))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatakeeperServices_ReplicateTo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatakeeperServicesServer).ReplicateTo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatakeeperServices_ReplicateTo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatakeeperServicesServer).ReplicateTo(ctx, req.(*ReplicateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DatakeeperServices_ServiceDesc is the grpc.ServiceDesc for DatakeeperServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DatakeeperServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DFS.DatakeeperServices",
	HandlerType: (*DatakeeperServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFileTransferState",
			Handler:    _DatakeeperServices_GetFileTransferState_Handler,
		},
		{
			MethodName: "ReplicateTo",
			Handler:    _DatakeeperServices_ReplicateTo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "datanode.proto",
}
