package KeeperNodes


const (
	SUCCESS = 200
	FAILED = 500
	NOT_FOUND = 404

	FILE_EXISTS = "FILE_ALREADY_EXISTS"
	NO_SUCH_FILE = "NO_SUCH_FILE"

	NO_AVAILABLE_DATA_KEEPER = "NO_AVAILABLE_DATA_KEEPER"
)

type FileState string
const (
	BEING_TRANSFERED FileState = "FILE_BEING_TRANSFERED"
	RESIDENT FileState = "RESIDENT"
	ABORTED FileState = "ABORTED"
)